name: DEPLOY TO STAGING
on: [workflow_dispatch]

jobs:
    aws-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: develop
            - uses: actions/setup-node@v1
              with:
                node-version: '16'
            - run: |
                echo "Running npm install"
                node --version
                npm --version
            - run: npm install
            - run: npm run build
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2.1.1
              env:
                    SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                    ARGS: "-rltgoDzvO --delete"
                    SOURCE: "dist/"
                    REMOTE_HOST: "ec2-54-91-7-9.compute-1.amazonaws.com"
                    REMOTE_USER: ubuntu
                    TARGET: "/var/www/html/survey-frontend"
